baseURL: https://chhanz88.github.io
disablePathToLower: true
languageCode: en-us
title: "chhanz 기술 블로그\n"
enableRobotsTXT: true
theme: "PaperMod"

params:
  showtoc: false
  comments: true
  assets:
    favicon: "https://chhanz88.github.io/assets/favicon.png"
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/chhanz"
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: About
      name: About
      url: /about/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
