baseURL: https://chhanz88.github.io/post/
disablePathToLower: true
languageCode: en-us
title: "chhanz 기술 블로그\n"
enableRobotsTXT: true
theme: "PaperMod"

params:
        #  env: production
  showtoc: false
  comments: true
  assets:
    favicon: "favicon.ico"
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/chhanz"
  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: Links
      name: Links
      url: /links/
      weight: 20
    - identifier: Archives 
      name: Archives 
      url: /archives 
      weight: 10
    - identifier: Search
      name: Search
      url: /search/
      weight: 30
    - identifier: About
      name: About
      url: /about/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
